# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use official lightweight Node.js image
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json ./

# Install dependencies without running install scripts
RUN npm install --ignore-scripts --silent

# Copy TypeScript config and source code
COPY tsconfig.json ./
COPY src ./src

# Build the TypeScript code
RUN npm run build --silent

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
